# Generated by Django 4.2.8 on 2024-12-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20231220_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['nombre'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='seccionprod',
            options={'ordering': ['nombre'], 'verbose_name': 'Sección de Producto', 'verbose_name_plural': 'Secciones de Productos'},
        ),
        migrations.AlterField(
            model_name='articulos',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='almacen', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del Artículo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.seccionprod', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='seccionprod',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='seccionprod',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Sección'),
        ),
        migrations.AlterField(
            model_name='seccionprod',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de Pedido')),
                ('fecha', models.DateField(verbose_name='Fecha del Pedido')),
                ('entregado', models.BooleanField(default=False, verbose_name='Entregado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
